name: CI
on:
  push:
    branches:
      - main
      - nixos-25.11
      - nixos-26.05
  pull_request:
    branches:
      - main
      - nixos-25.11
      - nixos-26.05
permissions: {}

env:
  REGISTRY: ghcr.io
  REPO_OWNER: ${{ github.repository_owner }}
  IMAGE_TAG: ${{ github.ref_name }}

jobs:
  check:
    name: Check flake
    runs-on: ubuntu-24.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: DeterminateSystems/flake-checker-action@3164002371bc90729c68af0e24d5aacf20d7c9f6 # v12

      - name: Check
        run: nix flake check

      - name: Format Nix
        run: nix fmt -- --check .

      - name: Lint YAML
        run: nix run nixpkgs#yamllint -- --format github --strict .

      - name: Format YAML
        run: nix run nixpkgs#yamlfmt -- -lint .

  build:
    name: Build and Push
    needs:
      - check
    permissions:
      id-token: "write"
      contents: "read"
      packages: "write"
    strategy:
      fail-fast: false
      matrix:
        variant:
          - "nix"
          - "lix"
        build:
          - runner: ubuntu-24.04
            architecture: amd64
          - runner: ubuntu-24.04-arm
            architecture: arm64
    runs-on: ${{ matrix.build.runner }}
    env:
      ARCHITECTURE: ${{ matrix.build.architecture }}
      VARIANT: ${{ matrix.variant }}

    steps:
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
        with:
          use-flakehub: false

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Build
        run: nix build -L ".#${VARIANT}"

      - name: Update /etc/containers/registries.conf
        run: |
          echo 'unqualified-search-registries = ["docker.io", "quay.io"]' | sudo tee /etc/containers/registries.conf

      - name: Login
        if: |
          github.ref_name == 'main' ||
          github.ref_name == 'nixos-25.11' ||
          github.ref_name == 'nixos-26.05'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          nix run nixpkgs#skopeo --
          login "${REGISTRY}"
          --username "${REPO_OWNER}"
          --password "${GH_TOKEN}"

      - name: Push
        if: |
          github.ref_name == 'main' ||
          github.ref_name == 'nixos-25.11' ||
          github.ref_name == 'nixos-26.05'
        run: >-
          nix run nixpkgs#skopeo --
          copy docker-archive:result
          docker://${REGISTRY}/${REPO_OWNER}/forgejo-${VARIANT}:${IMAGE_TAG}-${ARCHITECTURE}

  merge:
    name: Create and Push Manifest
    if: |
      github.ref_name == 'main' ||
      github.ref_name == 'nixos-25.11' ||
      github.ref_name == 'nixos-26.05'
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        variant: ["nix", "lix"]
    env:
      VARIANT: ${{ matrix.variant }}
    needs:
      - build
    permissions:
      id-token: "write"
      contents: "read"
      packages: "write"
    steps:
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
        with:
          use-flakehub: false

      # see https://github.com/actions/runner-images/issues/10443
      - run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Update /etc/containers/registries.conf
        run: |
          echo 'unqualified-search-registries = ["docker.io", "quay.io"]' | sudo tee /etc/containers/registries.conf

      - name: Login
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          nix run nixpkgs#buildah --
          login "${REGISTRY}"
          --username "${REPO_OWNER}"
          --password "${GH_TOKEN}"

      - name: Create manifest
        run: >-
          nix run nixpkgs#buildah --
          manifest create
          ${REGISTRY}/${REPO_OWNER}/forgejo-${VARIANT}:${IMAGE_TAG}
          ${REGISTRY}/${REPO_OWNER}/forgejo-${VARIANT}:${IMAGE_TAG}-amd64
          ${REGISTRY}/${REPO_OWNER}/forgejo-${VARIANT}:${IMAGE_TAG}-arm64

      - name: Push manifest
        run: >-
          nix run nixpkgs#buildah --
          manifest push
          ${REGISTRY}/${REPO_OWNER}/forgejo-${VARIANT}:${IMAGE_TAG}

      - name: Inspect image
        run: >-
          nix run nixpkgs#skopeo --
          inspect
          docker://${REGISTRY}/${REPO_OWNER}/forgejo-${VARIANT}:${IMAGE_TAG}

      - name: Fetch image digest
        id: digest
        run: >-
          nix run nixpkgs#skopeo --
          inspect
          --format 'digest={{ .Digest }}'
          docker://${REGISTRY}/${REPO_OWNER}/forgejo-${VARIANT}:${IMAGE_TAG}
          >> "${GITHUB_OUTPUT}"

      # https://github.com/sigstore/cosign/issues/587
      - name: Copy credentials for cosign
        run: |
          mkdir -p ~/.docker
          cp -v ${XDG_RUNTIME_DIR}/containers/auth.json ~/.docker/config.json

      - name: Sign image with static key
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          DIGEST: ${{ steps.digest.outputs.digest }}
        run: >-
          nix run nixpkgs#cosign --
          sign
          --yes
          --recursive
          --key env://COSIGN_PRIVATE_KEY
          -a "repo=${GITHUB_REPOSITORY}"
          -a "workflow=${GITHUB_WORKFLOW}"
          -a "ref=${GITHUB_SHA}"
          ${REGISTRY}/${REPO_OWNER}/forgejo-${VARIANT}:${IMAGE_TAG}@${DIGEST}

      - name: Sign with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.digest.outputs.digest }}
        run: >-
          nix run nixpkgs#cosign --
          sign
          --yes
          --recursive
          -a "repo=${GITHUB_REPOSITORY}"
          -a "workflow=${GITHUB_WORKFLOW}"
          -a "ref=${GITHUB_SHA}"
          ${REGISTRY}/${REPO_OWNER}/forgejo-${VARIANT}:${IMAGE_TAG}@${DIGEST}

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Verify image signatures
        env:
          DIGEST: ${{ steps.digest.outputs.digest }}
        run: >-
          nix run nixpkgs#cosign --
          verify
          --key cosign.pub
          ${REGISTRY}/${REPO_OWNER}/forgejo-${VARIANT}:${IMAGE_TAG}@${DIGEST}
